# Site Settings
title: MINJUNG
email: minjung.sw@gmail.com
description: Front-end Blog
baseurl: ""
url: "https://minjung-jeon.github.io"
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: MINJUNG
user_description: Front-end Developer
disqus_username: minjungs-blog

# Social Media
# Remove the item if you don't need it
github_username: minjung-jeon
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Web
    url: /menu/Web/
  - title: ECMAScript
    url: /menu/ECMAScript/
  - title: React
    url: /menu/React/
  - title: RxJS
    url: /menu/RxJS/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
